name: storm
description: Dart package for developing modern web server
version: 1.0.1+1
# homepage: https://www.example.com
repository: https://github.com/chandankumarshanbhag/Storm-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 path: ^1.7.0
 meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
