name: storm
description: A Dart package for developing modern web server
version: 1.0.1+3
# homepage: https://www.example.com
repository: https://github.com/chandankumarshanbhag/Storm-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
